saeta/penguin

- Sources/Penguin/CSVParsible.swift
- Sources/Penguin/TableCSV.swift
- Sources/Penguin/Trie.swift
- Sources/Penguin/TypedColumn.swift
- Tests/PenguinTests/CSVParsibleTests.swift
- Tests/PenguinTests/TableCSVTests.swift
- Tests/PenguinTests/TrieTests.swift
This PR introduces a `ColumnBuilder` abstraction which improves MovieLens parsing performance by 2x. The combination of `ColumnBuilder` and the `Trie` implementation results in a 3x performance improvement when parsing the criteo TSVs by avoiding unnecessary calls into Foundation.
Further, this PR also makes `PTypedColumn`'s compare semantically instead of comparing that the internal representations are the same. It also improves the correctness of number parsing in ints.
> Use a ColumnBuilder abstraction & a Trie

- Sources/PenguinGraphs/AdjacencyList.swift
- Sources/PenguinGraphs/PropertyMaps.swift
- Tests/PenguinGraphTests/AdjacencyListTests.swift
- Tests/PenguinGraphTests/InternalPropertyMapTests.swift
- Tests/PenguinGraphTests/ParallelExpanderTests.swift
- Tests/PenguinGraphTests/VertexParallelTests.swift
Follow-ups to https://github.com/saeta/penguin/pull/6
> Add `storing:` label to `addVertex(_:)` for all `MutablePropertyGraph`s

- Sources/Benchmarks/AdjacencyList.swift
- Sources/PenguinGraphs/BreadthFirstSearch.swift
- Sources/PenguinGraphs/DepthFirstSearch.swift
- Sources/PenguinGraphs/DijkstraSearch.swift
- Sources/PenguinGraphs/ParallelExpander.swift
- Sources/PenguinGraphs/PropertyMaps.swift
- Sources/PenguinGraphs/StrongComponents.swift
- Sources/PenguinGraphs/VertexParallelProtocols.swift
- Tests/PenguinGraphTests/DepthFirstSearchTests.swift
- Tests/PenguinGraphTests/DijkstraSearchTests.swift
- Tests/PenguinGraphTests/InternalPropertyMapTests.swift
- Tests/PenguinGraphTests/ParallelExpanderTests.swift
- Tests/PenguinGraphTests/VertexParallelTests.swift
Previously, things were separated into two parallel protocol families of
vertex property maps, and edge property maps. This made re-use of property
map implementations more difficult, as they had to be implemented for both
vertices as well as edges. Further, there was a non-trivial amount of
syntactic overhead for external property maps.
This change simplifies property maps by adding an extra associated type
to the base protocol. Once that has been added, it becomes trivial to
make an implementation that is generic over VertexId's and EdgeId's.
This has resulted in a significant simplification.
In addition, I've (for now) consolidated mutable and immutable property
map protocols into a single protocol. (This design decision might be
good to revisit in the future if this turns out to be …
> Simplify Property Map's

- Sources/PenguinParallel/NonblockingThreadPool/NonBlockingThreadPool.swift
The functionality referred to in the comment has been implemented in the
`PenguinParallelWithFoundation` package, which leverages the `Foundation`
dependency to query the number of available processors.
> Remove stale comment.

- Sources/PenguinParallel/NonblockingThreadPool/NonBlockingSpinningState.swift
- Sources/PenguinParallel/NonblockingThreadPool/NonBlockingThreadPool.swift
This change moves `NonBlockingSpinningState` to its own file to reduce the size of the
`NonBlockingThreadPool.swift` file.
> ComputeThreadPool cleanup (4/n): NonBlockingSpinningState to new file.

- Sources/PenguinParallel/NonblockingThreadPool/NonBlockingThreadPool.swift
- Sources/PenguinParallel/NonblockingThreadPool/NumberOperations.swift
The file NonBlockingThreadPool.swift is a little long, and has grown a few
utility functions within it that aren't tightly coupled to the implementation.
This change factors them out into an adjacent file to simplify maintenance of
the NonBlockingThreadPool.
> Factor out number operations from NonBlockingThreadPool.swift

- Sources/PenguinGraphs/DijkstraSearch.swift
- Sources/PenguinStructures/DefaultInitializable.swift
- Sources/PenguinStructures/Heap.swift
- Tests/PenguinGraphTests/DijkstraSearchTests.swift
- Tests/PenguinStructuresTests/HeapTests.swift
This change moves the heap related algorithms to operate generically on
`Collection` (and its various refinements). In doing so, the algorithms
become far more general and reusable.
Further, we re-build the PriorityQueue type, solving the indexing TODO's
that plagued the previous implementation.
Finally, we update all the rest of the code to use the new API.
> Rewrite the heap and related priority queue structures.

- Sources/PenguinStructures/Tuple.swift
- Tests/PenguinStructuresTests/TupleTests.swift
This is useful for writing functions that "map" an operation over a tuple.
e.g. in SwiftFusion, we have a tuple of variable assignment buffers and a tuple of indices and we need to produce a tuple of variable values. We can do this with a function that indexes the head buffer by the head index and then recursively calls itself on the tails. Then, this function needs to call `Tuple.init(head:tail:)` to produce its result.
> add recursive tuple initializer

- Sources/PenguinGraphs/ParallelExpander.swift
- Tests/PenguinGraphTests/ParallelExpanderTests.swift
This modification extends the expander algorithm family to support
graphs that contain vertices with no incoming edges. (Previously,
the presence of these vertices would trigger assertion failures.)
> [Parallel Expander] Support vertices with no in edges.

- Sources/PenguinStructures/Random.swift
- Tests/PenguinStructuresTests/RandomTests.swift
This PR adds:
- Doc comments
- Exposes the convenience method on RAC (otherwise the fast impl isn't
called on RAC's)
- Generalizes to all RAC's.
> Random sampling follow-on's.

- Sources/PenguinStructures/AnyArrayBuffer.swift
- Sources/PenguinStructures/ArrayBuffer.swift
- Tests/PenguinStructuresTests/ArrayStorageExtensionTests.swift
* Adds `withUnsafeRaw[Mutable]BaseAddress` to `AnyArrayBuffer` so that we can get the memory of a type-erased array buffer.
* Makes `AnyArrayBuffer.storage` and `ArrayBuffer.storage` public so that element-specific extensions can implement element-specific operations by delegating to the element-specific operations on the `storage`.
* Adds `AnyArrayBuffer.ensureUniqueStorage()` and `ArrayBuffer.ensureUniqueStorage()` to make it easier to implement methods that mutate the storage.
> add methods & properties for accessing and mutating [Any]ArrayBuffer

- Sources/PenguinGraphs/AdjacencyList.swift
- Sources/PenguinGraphs/GraphProtocol.swift
- Sources/PenguinStructures/CollectionAlgorithms.swift
- Tests/PenguinGraphTests/AdjacencyListTests.swift
- Tests/PenguinStructuresTests/CollectionAlgorithmTests.swift
- Tests/PenguinStructuresTests/XCTestManifests.swift
Previously, the AdjacencyList implementation punted on the implementation
of some graph mutation operations (such as removing an edge or a vertex.
This change adds implementations for a number of these operations (but
not yet all).
> Support AdjacencyList removal mutations.

- Sources/PenguinStructures/AnyArrayBuffer.swift
- Sources/PenguinStructures/ArrayStorage.swift
Preparing for SwiftFusion migration, will come back to strip out raw pointer operations and update tests.
> More work refactoring [Any]Array[Storage|Buffer] to avoid dynamic dispatch

- Sources/PenguinStructures/AnyArrayBuffer.swift
These are the cast operations used in https://github.com/borglab/SwiftFusion/pull/79.
> AnyArrayBuffer cast operations

- Sources/Benchmarks/ParallelExpanderBenchmarks.swift
- Sources/PenguinGraphs/VertexParallelProtocols.swift
- Sources/PenguinParallel/ConcurrencyPlatform.swift
- Sources/PenguinParallel/NonblockingThreadPool/NonBlockingThreadPool.swift
- Sources/PenguinParallel/ThreadPool.swift
- Sources/PenguinPipeline/Pipeline/GeneratorPipelineIterator.swift
- Sources/PenguinStructures/Type.swift
- Tests/PenguinGraphTests/AdjacencyListTests.swift
- Tests/PenguinGraphTests/ParallelExpanderTests.swift
- Tests/PenguinGraphTests/VertexParallelTests.swift
- Tests/PenguinParallelTests/PosixConcurrencyPlatformTests.swift
- Tests/PenguinPipelineTests/FunctionGeneratorPipelineIteratorTests.swift
- Tests/PenguinPipelineTests/PrefetchPipelineIteratorTests.swift
Very mechanical change whose motivation is explained in the doc comment for Type.swift, in the commit
> Use Type<T>() instead of T.self

- Sources/PenguinStructures/FixedSizeArray.swift
`Self` doesn't contain elements; it's a type, and “static” could mean lots of
things in this context.  The fact that it is the same as part of the
declaration, which is apparent to anyone reading the comment just like type
information would be, makes it potentially confusing.
> Make doc comments reflect semantics, not language construct.

- Sources/PenguinStructures/AnyArrayBuffer.swift
- Sources/PenguinStructures/ArrayStorage.swift
- Tests/PenguinStructuresTests/ArrayStorageExtensionTests.swift
This should reduce the boilerplate somewhat, even aside from removing the `@_specialize` annotations.
> AnyArrayBuffer with operations that specialize properly.

- Sources/Benchmarks/ArrayStorage.swift
- Sources/PenguinStructures/AnyArrayBuffer.swift
- Sources/PenguinStructures/ArrayBuffer.swift
- Sources/PenguinStructures/ArrayStorage.swift
- Sources/PenguinStructures/FactoryInitializable.swift
- Sources/PenguinStructures/Type.swift
- Tests/PenguinStructuresTests/ArrayBufferTests.swift
- Tests/PenguinStructuresTests/ArrayStorageExtensionTests.swift
- Tests/PenguinStructuresTests/ArrayStorageTests+Internal.swift
- Tests/PenguinStructuresTests/ArrayStorageTests.swift
- Makes construction of empty `Array`[`Buffer`|`Storage`] super-efficient
- Could removes optionality of storage in `AnyArrayBuffer` but for ARC optimizer weakness
- Will allow us to create a zero tensor in type-erased storage (in SwiftFusion) without knowing the element type.
Note that because the dynamic class type of an `AnyArrayStorage` captures aspects of its `Element` type, it becomes important not to expose those derived class instances as extension point if we are aliasing an instance of fake dynamic element type.  Therefore `ArrayStorage<T>` becomes a `struct` in this PR.
589% speedup observed in empty `ArrayStorage` creation.
> Add canonical zero-capacity ArrayStorage instance.

- Sources/PenguinStructures/AnyArrayBuffer.swift
- Tests/PenguinStructuresTests/AnyArrayBufferTests.swift
Gives us one consistent way to downcast for read, write, or modification of the typed `ArrayBuffer` associated with an `AnyArrayBuffer`.
> Add subscripts for typed access to AnyArrayBuffer.

- Sources/PenguinTesting/StdlibProtocolTests.swift
- Tests/PenguinStructuresTests/ArrayBufferTests.swift
- Tests/PenguinStructuresTests/ArrayStorageExtensionTests.swift
- Tests/PenguinStructuresTests/ArrayStorageTests.swift
- Tests/PenguinStructuresTests/ConcatenationTests.swift
- Tests/PenguinStructuresTests/EitherTests.swift
- Tests/PenguinStructuresTests/FixedSizeArrayTests.swift
- Tests/PenguinStructuresTests/NominalElementDictionaryTests.swift
Also improve some names.
@marcrasi this should allow you to test those `Scalars` for whatever refined `Collection` semantics they're declared to have.
> PenguinTesting: add checkDeclaredSequenceRefinementSemantics

- Package.resolved
- Sources/Benchmarks/AnyValueBenchmarks.swift
- Sources/Benchmarks/ConcurrencyPlatform.swift
- Sources/Benchmarks/NonBlockingCondition.swift
- Sources/Benchmarks/NonBlockingThreadPool.swift
- Sources/Benchmarks/PosixConcurrencyPlatform.swift
- Sources/Benchmarks/ThreadLocalStorage.swift
- Sources/PenguinStructures/AnyValue.swift
- Tests/PenguinStructuresTests/AnyValueTestable.swift
- Tests/PenguinStructuresTests/AnyValueTests.swift
- Tests/PenguinStructuresTests/FactoryInitializableTests.swift
- Tests/PenguinStructuresTests/XCTestManifests.swift
OMG this was so hard to get right, you don't even know.
Note: see commit messages for progression of results.
```
swift run -c release -Xswiftc -cross-module-optimization Benchmarks --warmup-iterations 2 --filter AnyValue
name                                             time            std        iterations warmup      
---------------------------------------------------------------------------------------------------
AnyValue.erased [Int] sum                             6695608 ns ±   3.24 %        210  15740437 ns
AnyValue.erased [Int] swapHalves                      1591548 ns ±   6.03 %        858   3213536 ns
AnyValue.erased [Int]x2 sum                       3812041.500 ns ±   4.37 %        362   7813602 ns
AnyValue.erased [Int]x2 swapHalves                5092725.500 ns ±   4.47 % …
```
> Add AnyValue

- Sources/PenguinStructures/Lens.swift
- Sources/PenguinStructures/Projections.swift
- Tests/PenguinStructuresTests/ProjectionTests.swift
Adds a view that projects a part of another sequence's elements.  This will be useful for `InsertionOrderedDictionary`'s `keys` and `values` views.
> Add Lens and Projections.

- Package.swift
This should make it possible to build packages that depend on multiple packages that depend on different version ranges of swift-benchmark (as long as there is at least one compatible version).
> make swift-benchmark dependency use version

- Sources/PenguinStructures/AnyValue.swift
See #131 for description of the crash.
This can probably be reduced into a simple crasher that can be filed against the Swift compiler, but I haven't tried because I don't know much about what this code is doing and what parts are likely to be triggering this problem.
I ran the AnyValue benchmarks (using the tensorflow-0.11 toolchain) on master vs this PR:
```
master                                         this pr
name                                             time       std        iterations               time       std        iterations
--------------------------------------------------------------------------------------------------------------------------------
AnyValue.erased [Int] sum                         62.507 ms ±   0.23 %         22                61.576 ms ±   0.20 % …
```
> workaround compile crash

- Sources/PenguinTables/TableSchema.swift
Previously, PenguinTable's TableSchema conditionally depended upon
`KeyPathIterable` to automatically implement some functionality.
After S4TF 0.12, S4TF moved to a different implementation of KeyPathIterable,
and as a result, KeyPathIterable is no longer included in the standard library.
This causes compilation errors in Penguin.
This change disables the conditional use of KeyPathIterable and future work can
refactor the implementation to use the new S4TF-contributed reflection APIs.
Fixes: #142.
> Disable KeyPathIterable
